# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f904ccbfcbcb0a1ead40906357e6f715bf2b6c26d179d4939120d1967755407b7ebb26df262e9a62026c57dd98d8542619c80588160d9d2de2a8fa1b353d07a

test:
  secret_key_base: 7b678552c351ad938ad0266fba58a293a118e95c4186c060045db79d71ebf77f916f1ade738179158fb621966e16dd193669aaf681a0b9990b33c1e90bfda897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
